### PR TITLE
Heartbranch

### PR DESCRIPTION
**Pull request by sujin16**
i want to merge  heart branch !!!

### CODE REVIEW

**Comment by sujin16** [comment]
Merge heart branch

**Comment by sujin16** [comment]
please merge heart branch

**Comment by sujin16** [comment]
commit merge heart branch

**Comment by jieun1114** [comment]
okay

**Review by sujin16 — COMMENTED** [review]
finish heart activity

**Comment by sujin16** [comment]
merge heart branch

**Comment by sujin16** [comment]
i want merge please

**Comment by sujin16** [comment]
merge please

**Comment by jieun1114** [comment]
merge

**Comment by sujin16** [comment]
Merge heartBranch

**Review by jieun1114 — COMMENTED** [review]
good

**Comment by sujin16** [comment]
Merge heartBranch

**Comment by jieun1114** [comment]
merge

**Review by jieun1114 — APPROVED** [review]
merge

**Comment by sujin16** [comment]
merge heart branch

**Comment by jieun1114** [comment]
why not?

**Comment by sujin16** [comment]
Merge Heartbranch

**Comment by sujin16** [comment]
Merge heartbranch

**Pull request closed without merging**
